### ISSUE TITLE
Failed to instantiate module IonicModalNav

### ISSUE THREAD

**Issue by zeeshan-m** [trazek/ionic-modal-nav-example#1]
Can't seem to get IonicModalNav to work properly. Code is below:

```
angular.module('blah.controllers', ['ionic','blah.services','ngCordova','blah.utils', 'IonicModalNav'])

.controller('MainCtrl', ['$scope', '$location','$stateParams', '$ionicModal', 'IonicModalNavService') {
$scope.openPreferenceSelector = function(type) {
       IonicModalNavService.go('blahselector');
}
```

Any idea why? "ionic-modal-nav": "^1.0.4" is included in my package.json and it's installed. 

I'm using ionic 1.3.1 if that makes a difference.

**Comment by trazek** [comment]
My guess is the way it's being loaded into your project. If you are loading
using ES6 imports, you'll need to do:

import 'ionic-modal-nav';

As shown here:


'use strict';
import {BaseComponent} from 'components/base/base';
import {NextBaseComponent} from 'components/nextBase/nextBase';
import {ModalViewAComponent} from 'components/modal-viewA/modal-viewA';
import {ModalViewBComponent} from 'components/modal-viewB/modal-viewB';
import 'ionic-modal-nav';
angular.module('app', [
'ionic',
'app.run',
'app.components',
'app.states',
'IonicModalNav'
]);

Otherwise, you will have to include the script directly, adding the path in
a script tag:

<script src='node_modules/ionic-modal-nav/src/ionic-modal-nav.js' ></script>

Hopefully that helps. Thanks for emailing.

Cheers,

- Andrew

**Comment by trazek** [comment]
My guess is the way it's being loaded into your project. If you are loading using ES6 imports, you'll need to do:

`import 'ionic-modal-nav';`

As shown here:

```
'use strict';

import {BaseComponent} from 'components/base/base';
import {NextBaseComponent} from 'components/nextBase/nextBase';

import {ModalViewAComponent} from 'components/modal-viewA/modal-viewA';
import {ModalViewBComponent} from 'components/modal-viewB/modal-viewB';

import 'ionic-modal-nav';

angular.module('app', [
    'ionic',
    'app.run',
    'app.components',
    'app.states',
    'IonicModalNav'
]);
```

Otherwise, you will have to include the script directly, adding the path in a script tag:

`<script src='node_modules/ionic-modal-nav/index.js' ></script>`

If your application supports ES6, you can also include the file in the `src` directory. 

Perhaps I will include a ES5 version also soon. My apologizes.

Hopefully that helps.

Cheers,
- Andrew

**Comment by zeeshan-m** [comment]
Other than updating to ES6 is there nothing I can do to get this to work?

**Comment by trazek** [comment]
If you update the ionic-modal-nav module, I added a `dist` folder with a minified file called `ionic-modal-nav.min.js`. You can either reference it directly in a `script` tag in your index.html file or setup a `gulp` task or something to copy the file where ever your public directory.

I will edit the example repo with more instruction on how to use the module for non-ES6 users.

Thanks!

-Andrew

**Comment by trazek** [comment]
Yeah. Try loading the script directly from the `node_modules` folder, referencing the `index.js` file:

`<script src='node_modules/ionic-modal-nav/index.js' ></script>`

**Comment by zeeshan-m** [comment]
Loading index.js and ionic-modal-nav.min.js still leads to a 

```
ReferenceError: exports is not defined
```

error. I don't think you can directly include it with ES6, I'm pretty sure it still needs to transpile it into ES5. I'll see if I can get something working.

**Comment by zeeshan-m** [comment]
I used browserify to transpile it into ES5 ([gist here](https://gist.github.com/zeeshan-m/f4529fd9ead53314aecc4f615d636dc2)). Now it loads fine but doesn't work properly. My app.js includes:

```
.state('app.clubselector', {
      views: {
          'ionic-modal-nav@': {
          templateUrl: 'templates/clubselector.html',
          controller:'MainCtrl'
          }
      }
})
```

I'm calling it using:

```
IonicModalNavService.go('app.clubselector');
```

Based on console debugging it looks like it is loaded somewhere, but not in the modal or the original app itself. Any idea what's happening?

**Comment by trazek** [comment]
Glad you got it to load properly. To open the modal and load an initial state, you need to call `
IonicModalNavService.show(modalState)`. Once inside the ionic-modal-nav, you can call 
`IonicModalNavService.go(modalState, data)` to move forward within the modal

**Comment by trazek** [comment]
I published the transpiled fie you referenced to the module under in the `dist` directory, called `ionic-modal-nav-es5.js`. Hopefully this helps others and thanks again.

**Comment by zeeshan-m** [comment]
Thanks for your help! :)

**Comment by trazek** [comment]
My pleasure. Let me know if anything else crops up
